"""Curated quotes for the 'quote' command. Bundled locally so it works
without internet (third-party free quote APIs like quotable.io have proven
unreliable / shut down over time)."""

QUOTES = [
    ("Het is niet de sterkste soort die overleeft, ook niet de intelligentste, maar degene die zich het best aanpast aan verandering.", "Charles Darwin"),
    ("Ik denk, dus ik besta.", "René Descartes"),
    ("De enige manier om geweldig werk te doen, is te houden van wat je doet.", "Steve Jobs"),
    ("In het midden van moeilijkheden ligt de kans.", "Albert Einstein"),
    ("Alles wat je kunt je voorstellen is echt.", "Pablo Picasso"),
    ("Geluk is niet iets kant-en-klaars. Het komt voort uit je eigen daden.", "Dalai Lama"),
    ("De weg naar het geluk voert langs twee grondbeginselen: interesse en volharding.", "John Dewey"),
    ("Het leven is wat er gebeurt terwijl je andere plannen aan het maken bent.", "John Lennon"),
    ("Wees de verandering die je in de wereld wilt zien.", "Mahatma Gandhi"),
    ("Twijfel niet aan jezelf, dat doen anderen al genoeg.", "Onbekend"),
    ("Een reis van duizend mijl begint met een enkele stap.", "Lao Tzu"),
    ("Het enige wat we hoeven te vrezen, is de vrees zelf.", "Franklin D. Roosevelt"),
    ("Kennis is macht.", "Francis Bacon"),
    ("Wie A zegt, moet ook B zeggen.", "Nederlands spreekwoord"),
    ("Beter een vogel in de hand dan tien in de lucht.", "Nederlands spreekwoord"),
    ("De aanhouder wint.", "Nederlands spreekwoord"),
    ("Zachte heelmeesters maken stinkende wonden.", "Nederlands spreekwoord"),
    ("Wie niet waagt, die niet wint.", "Nederlands spreekwoord"),
    ("Success is not final, failure is not fatal: it is the courage to continue that counts.", "Winston Churchill"),
    ("The only way to do great work is to love what you do.", "Steve Jobs"),
    ("It always seems impossible until it's done.", "Nelson Mandela"),
    ("Simplicity is the ultimate sophistication.", "Leonardo da Vinci"),
    ("Stay hungry, stay foolish.", "Steve Jobs"),
    ("The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"),
    ("Not all those who wander are lost.", "J.R.R. Tolkien"),
    ("What we know is a drop, what we don't know is an ocean.", "Isaac Newton"),
    ("Genius is one percent inspiration and ninety-nine percent perspiration.", "Thomas Edison"),
    ("If you want to go fast, go alone. If you want to go far, go together.", "Afrikaans spreekwoord"),
    ("A ship in harbor is safe, but that is not what ships are built for.", "John A. Shedd"),
    ("Whether you think you can or think you can't, you're right.", "Henry Ford"),
    ("De grootste glorie ligt niet in nooit vallen, maar in elke keer opstaan.", "Confucius"),
    ("Doe wat je kan, met wat je hebt, waar je bent.", "Theodore Roosevelt"),
    ("Een goed begin is het halve werk.", "Nederlands spreekwoord"),
    ("Wie het kleine niet eert, is het grote niet weerd.", "Nederlands spreekwoord"),
    ("Al doende leert men.", "Nederlands spreekwoord"),
    ("Geduld is een schone zaak.", "Nederlands spreekwoord"),
    ("Onbekend maakt onbemind.", "Nederlands spreekwoord"),
    ("Where there is no struggle, there is no strength.", "Oprah Winfrey"),
    ("The best time to plant a tree was 20 years ago. The second best time is now.", "Chinees spreekwoord"),
    ("Turn your wounds into wisdom.", "Oprah Winfrey"),
    ("Ver weg is dichtbij als je maar doorzet.", "Onbekend"),
    ("Muziek verzacht de zeden.", "William Congreve"),
    ("Verbeelding is belangrijker dan kennis.", "Albert Einstein"),
    ("Twee weten meer dan een.", "Nederlands spreekwoord"),
    ("Alle begin is moeilijk.", "Nederlands spreekwoord"),
    ("Zonder wrijving geen glans.", "Nederlands spreekwoord"),
    ("You miss 100% of the shots you don't take.", "Wayne Gretzky"),
    ("In the middle of every difficulty lies opportunity.", "Albert Einstein"),
    ("Be yourself; everyone else is already taken.", "Oscar Wilde"),
    ("Ga niet waar het pad je leidt, ga liever waar geen pad is en laat een spoor achter.", "Ralph Waldo Emerson"),
    ("Alleen ga je sneller, samen kom je verder.", "Afrikaans spreekwoord"),
    ("Blaffende honden bijten niet.", "Nederlands spreekwoord"),
    ("Wie kaatst, moet de bal verwachten.", "Nederlands spreekwoord"),
    ("Elk nadeel heb z'n voordeel.", "Johan Cruijff"),
    ("Je gaat het pas zien als je het doorhebt.", "Johan Cruijff"),
    ("Voetballen is heel simpel, maar het simpelste is het moeilijkste dat er is.", "Johan Cruijff"),
    ("Kwaliteit is nooit een toeval; het is altijd het resultaat van intelligente inspanning.", "John Ruskin"),
    ("Doe wat juist is, niet wat makkelijk is.", "Onbekend"),
    ("De beste tijd om te beginnen was gisteren. De op één na beste tijd is nu.", "Onbekend"),
    ("Vallen kan iedereen, opstaan is de kunst.", "Onbekend"),
]
