"""Dutch did-you-know facts for the 'weetje' command. Each one fits a single mesh message (at most 125 bytes)."""

WEETJES = [
    "Weetje: ongeveer een kwart van Nederland ligt onder zeeniveau.",
    "Weetje: het laagste punt van Nederland ligt bij Nieuwerkerk aan den IJssel, bijna 7 meter onder NAP.",
    "Weetje: het hoogste punt van Nederland (zonder Caribisch deel) is de Vaalserberg, ruim 320 meter.",
    "Weetje: de Afsluitdijk is ruim 32 km lang en werd in 1932 gesloten.",
    "Weetje: Nederland heeft meer fietsen dan inwoners.",
    "Weetje: NAP staat voor Normaal Amsterdams Peil.",
    "Weetje: de Deltawerken beschermen Zeeland en Zuid-Holland sinds de ramp van 1953.",
    "Weetje: Flevoland is de jongste provincie van Nederland, opgericht in 1986.",
    "Weetje: Amsterdam is de hoofdstad, maar de regering zit in Den Haag.",
    "Weetje: het Wilhelmus is een van de oudste volksliederen ter wereld.",
    "Weetje: de tulp komt oorspronkelijk uit Centraal-Azië, niet uit Nederland.",
    "Weetje: de Elfstedentocht is ongeveer 200 km lang en werd voor het laatst gereden in 1997.",
    "Weetje: de eerste telescoop werd rond 1608 in Middelburg beschreven.",
    "Weetje: Antoni van Leeuwenhoek uit Delft zag als een van de eersten bacteriën door zijn microscoop.",
    "Weetje: Christiaan Huygens vond in 1656 het slingeruurwerk uit.",
    "Weetje: de cd werd ontwikkeld door Philips samen met Sony.",
    "Weetje: wifi bouwt voort op werk van Vic Hayes en een team bij NCR in Nieuwegein.",
    "Weetje: bluetooth werd bij Ericsson ontwikkeld, met Jaap Haartsen uit Nederland als grondlegger.",
    "Weetje: LoRa staat voor Long Range.",
    "Weetje: LoRa-radio werkt nog als het signaal onder de ruis zit: een negatieve SNR is heel normaal.",
    "Weetje: 868 MHz is in Europa een vrije band, maar je mag er maar een klein deel van de tijd zenden.",
    "Weetje: een hogere spreading factor geeft meer bereik, maar elk bericht duurt dan langer in de lucht.",
    "Weetje: radiogolven op 868 MHz hebben een golflengte van ongeveer 35 cm.",
    "Weetje: een repeater hoog op een gebouw hoort vaak tientallen kilometers ver.",
    "Weetje: de aarde is vanaf 2 meter hoogte maar zo'n 5 km ver te zien; daarom helpt een hoge antenne zo veel.",
    "Weetje: licht doet ongeveer 8 minuten en 20 seconden over de reis van de zon naar de aarde.",
    "Weetje: de maan staat gemiddeld zo'n 384.000 km van de aarde.",
    "Weetje: van de maan zie je altijd dezelfde kant, omdat hij even snel draait als hij rond de aarde gaat.",
    "Weetje: een dag op Venus duurt langer dan een jaar op Venus.",
    "Weetje: Jupiter is zo groot dat alle andere planeten er samen in zouden passen.",
    "Weetje: het ISS draait in ongeveer 90 minuten een rondje om de aarde.",
    "Weetje: bliksem is ongeveer vijf keer zo heet als het oppervlak van de zon.",
    "Weetje: tel de seconden tussen bliksem en donder en deel door 3: dat is ongeveer de afstand in km.",
    "Weetje: een regenboog zie je alleen met de zon in je rug.",
    "Weetje: water is het zwaarst bij ongeveer 4 graden, daarom bevriest een meer van boven naar beneden.",
    "Weetje: de octopus heeft drie harten en blauw bloed.",
    "Weetje: honingbijen communiceren met een dansje dat de richting van voedsel aangeeft.",
    "Weetje: een ooievaar vliegt in de winter tot in Afrika en keert vaak terug naar hetzelfde nest.",
    "Weetje: de koekoek legt haar eieren in de nesten van andere vogels.",
    "Weetje: een eekhoorn vindt lang niet al zijn verstopte nootjes terug; zo helpt hij bomen groeien.",
    "Weetje: een giraffe heeft net als wij zeven nekwervels.",
    "Weetje: haaien bestonden al voor er bomen waren.",
    "Weetje: bananen zijn botanisch gezien bessen, aardbeien niet.",
    "Weetje: honing bederft niet; in Egyptische graven is eeuwenoude honing gevonden.",
    "Weetje: de stroopwafel komt uit Gouda.",
    "Weetje: hagelslag is een Nederlandse uitvinding uit de jaren '30.",
    "Weetje: de oranje wortel werd populair in Nederland; eerder waren wortels vaak paars of geel.",
    "Weetje: de Nederlandse kustlijn is ruim 400 km lang.",
    "Weetje: de Waddenzee staat op de werelderfgoedlijst van UNESCO.",
    "Weetje: de Kinderdijk heeft 19 molens en staat op de werelderfgoedlijst.",
    "Weetje: in Nederland staan nog ruim 1000 historische molens.",
    "Weetje: de Maas ontspringt in Frankrijk en is ongeveer 925 km lang.",
    "Weetje: de Rijn komt uit Zwitserland en is ongeveer 1230 km lang.",
    "Weetje: morsecode heeft voor de letter E maar één punt, omdat die het vaakst voorkomt in het Engels.",
    "Weetje: SOS in morse is ...---... en betekent eigenlijk niets; het is gekozen omdat het makkelijk te herkennen is.",
    "Weetje: 112 werkt in de hele Europese Unie.",
    "Weetje: de eerste sms werd in 1992 verstuurd en luidde: Merry Christmas.",
    "Weetje: het eerste mobieltje (1973) woog ruim een kilo.",
    "Weetje: een QR-code blijft leesbaar als een deel beschadigd is, dankzij foutcorrectie.",
    "Weetje: het woord robot komt uit een Tsjechisch toneelstuk uit 1920.",
    "Weetje: de eerste computerbug was een echte mot, in 1947 gevonden in een Harvard-computer.",
]
